In [1]:
import numpy as np

arange()

In [6]:
arr1 = np.arange(10)
arr2 = np.arange(10, 20)
arr3 = np.arange(10, 20, 2)
arr4 = np.arange(10, 20, 1.4)
arr4

array([10. , 11.4, 12.8, 14.2, 15.6, 17. , 18.4, 19.8])

linspace()

In [5]:
arr5 = np.linspace(10, 20, 11)

arr6 = np.linspace(10, 20, 101)

arr7 = np.linspace(0, np.pi, 100)
arr7


array([0.        , 0.03173326, 0.06346652, 0.09519978, 0.12693304,
       0.1586663 , 0.19039955, 0.22213281, 0.25386607, 0.28559933,
       0.31733259, 0.34906585, 0.38079911, 0.41253237, 0.44426563,
       0.47599889, 0.50773215, 0.53946541, 0.57119866, 0.60293192,
       0.63466518, 0.66639844, 0.6981317 , 0.72986496, 0.76159822,
       0.79333148, 0.82506474, 0.856798  , 0.88853126, 0.92026451,
       0.95199777, 0.98373103, 1.01546429, 1.04719755, 1.07893081,
       1.11066407, 1.14239733, 1.17413059, 1.20586385, 1.23759711,
       1.26933037, 1.30106362, 1.33279688, 1.36453014, 1.3962634 ,
       1.42799666, 1.45972992, 1.49146318, 1.52319644, 1.5549297 ,
       1.58666296, 1.61839622, 1.65012947, 1.68186273, 1.71359599,
       1.74532925, 1.77706251, 1.80879577, 1.84052903, 1.87226229,
       1.90399555, 1.93572881, 1.96746207, 1.99919533, 2.03092858,
       2.06266184, 2.0943951 , 2.12612836, 2.15786162, 2.18959488,
       2.22132814, 2.2530614 , 2.28479466, 2.31652792, 2.34826

matriz

In [7]:
minhaMatriz = np.array([[1,2,3], [4,5,6]])
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
minhaLista = [[13,81,22], [0, 34, 59], [21, 48, 94]]
minhaMatriz = np.matrix(minhaLista)
minhaMatriz

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [9]:
x = np.zeros(3)
x

array([0., 0., 0.])

In [10]:
x = np.zeros((3,2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
print(np.zeros(3))

[0. 0. 0.]


In [12]:
print(np.zeros((3, 2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
x = np.ones((5,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

Desafio: como obter uma matriz 4x4 apenas com
números 8?

In [17]:
np.full((4, 4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [18]:
z = np.diag(np.array([1, 2, 3, 4, 5, 6]))
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [19]:
y = np.eye(5)
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
y = np.eye(5, dtype= int)
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [21]:
minhaMatriz.shape

(3, 3)

In [22]:
type(minhaMatriz)

numpy.matrix

In [25]:
minhaMatriz.dtype

dtype('int64')

In [26]:
minhaMatriz[2, 1]

48

In [27]:
print(minhaMatriz[0,:])

[[13 81 22]]


In [28]:
print(minhaMatriz[:,2])

[[22]
 [59]
 [94]]


In [29]:
minhaMatriz[1,0] = 100
minhaMatriz

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

In [31]:
np.sum(minhaMatriz)

472

In [32]:
np.prod(minhaMatriz)

440321981299200

In [33]:
np.cumsum(minhaMatriz)

matrix([[ 13,  94, 116, 216, 250, 309, 330, 378, 472]])

In [34]:
minhaMatriz.min()

13

In [35]:
minhaMatriz.max()

100

In [37]:
np.mean(minhaMatriz)

52.44444444444444

In [38]:
np.median(minhaMatriz)

matrix([[ 21.,  13.,  22.,  34.,  48.,  59.,  81.,  94., 100.]])

In [39]:
np.var(minhaMatriz)

964.246913580247

In [41]:
np.std(minhaMatriz)

31.052325413409008

Desafio

In [43]:
# criando um array unidimensional com 20 elementos
desafio = np.arange(20)
desafio

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
# varrendo array e buscando pares
for i in desafio:
    if i % 2 == 0:
        print(i)

0
2
4
6
8
10
12
14
16
18


In [46]:
# buscando impares
for i in desafio:
    if i % 2 != 0:
        print(i)

1
3
5
7
9
11
13
15
17
19


In [48]:
# obtendo media, soma, produto, variancia e desvio

print(np.mean(desafio))
print(np.sum(desafio))
print(np.prod(desafio))
print(np.var(desafio))
print(np.std(desafio))

9.5
190
0
33.25
5.766281297335398


In [50]:
# Buscando os números maiores que 5
for num in desafio:
    if num > 5:
        print(num)

6
7
8
9
10
11
12
13
14
15
16
17
18
19
