# Aula 6

### NumPy

In [1]:
import numpy as np

In [2]:
minha_lista = [0, 1, 2, 3, 4, 5, 6, 7, 8]
minha_lista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
array_numpy = np.array(minha_lista)
array_numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
print(array_numpy)

[0 1 2 3 4 5 6 7 8]


In [7]:
minha_lista = list(range(9))
minha_lista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [8]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
array2 = np.arange(9)
print(array2)

[0 1 2 3 4 5 6 7 8]


In [11]:
array3 = np.arange(0, 10, 0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [13]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [20]:
array3 = np.arange(0, 10, 0.5, dtype=int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [23]:
type(array4)

numpy.ndarray

In [24]:
array4.dtype

dtype('float64')

In [34]:
vetor1 = np.array([0, 1, 2, 3, 4])
print(vetor1)

[0 1 2 3 4]


In [27]:
vetor1[3]

3

In [28]:
vetor1[0:2]

array([0, 1])

In [29]:
print(vetor1[0:2])

[0 1]


In [30]:
s = np.array(['Python', 'Profissional', 'Java', 'Água'])
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [31]:
s = np.array(['Python', 'Profissional', 1464321315, 'Java', 'Água'])
s

array(['Python', 'Profissional', '1464321315', 'Java', 'Água'],
      dtype='<U21')

In [35]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

In [36]:
vetor1[0] = 'Novo elemento' 

ValueError: invalid literal for int() with base 10: 'Novo elemento'

In [37]:
vetor1[0] = 45.6
vetor1

array([45,  1, 10,  3,  4])